#! /usr/bin/env ruby

require 'choice'
require 'open-uri'
require 'openssl'
require 'logger'
require 'socket'

class CFBypass

  def hosts_to_a(path, logger)
    logger.info 'Enumerating Targets...'
    open(path.strip) { |f| f.read }
  end

  def run (file_contents, logger)
    subs = ['cpanel', 'ftp', 'admin', 'vpn', 'irc', 'jabber', 'xmpp', 'mail', 'smtp', 'imap', 'pop', 'pop3', 'ssh', 'telnet', 'www1', 'ww1', 'www2', 'ww2',]
    logger.info 'Scanning targets...'
    puts ''
    err = []
    succ = []
    fail = []
    file_contents.each_line do |line|
      # Clean the target string
      line = line.strip
      begin
        cf_host_ip = IPSocket.getaddress(line).inspect.to_s
        cf_info = "[CloudFlare IP]: #{cf_host_ip.strip} - #{line}"
        new_arr = []
        subs.each do |sub|
          begin
            real_ip = IPSocket.getaddress(sub+'.'+line).inspect.to_s
            if real_ip === cf_host_ip
              fail << "#{sub+'.'+line} has the same ip as #{line} : #{cf_host_ip} : real ip not found"
            else
              new_arr << "[Possible real IP]: #{real_ip.strip} - #{sub+'.'+line}"
            end
          rescue
            #logger.warn "Cloud not get IP for: #{sub+'.'+line}"
          end
        end
        if !new_arr.empty?
          succ << cf_info
          new_arr.each do |l|
            succ << l
          end
          succ << " "
        end
      rescue
        err << "Cloud not get CloudFlare IP for: #{line}"
      end
    end
    if !succ.empty?
      logger.info 'The following are results are potential real results: '
      succ.each do |s|
        logger.info s
      end
      puts "\n"
    end
    if !fail.empty?
      logger.info 'The following domains did not return any results: '
      fail.each do |f|
        logger.warn f
      end
      puts "\n"
    end
    if !err.empty?
      logger.info 'The following errors occurred: '
      err.each do |e|
        logger.error e
      end
    end
  end
end


puts '
...................................:7$.....~777II?+?77777....=7?....................................
..................................O?Z78..777::::::::::::+77,OIZ78...................................
................................:7Z+,,ZI87~~~~~~~~~~~~~:~:77Z:::ZZO..=....................... ......
.................................Z,,,,,=$8===============~$O~~~~~Z$8,~..~...........................
.............................7=Z:::::::::Z?8?7777777777,.Z~========OI8+?............................
............................87Z::::~~~~~~~~O877777777I=ZZ======+++++7Z8.+I..........................
..........................7IZ:~~~~~~~~~~====ZI877777O+Z++++++++??????IZ?O..,........................
..........................IZ=~===========+++++Z8ZIIOZ7?????????IIIIIIIIZII..........................
.........................+7=ZZ=+++++++++???????I$ZIZIIIIIIIIII7777777OZ?III7+.......................
.........................77?7IZ7+????????IIIIIIIIZIII7777777777$$$$$O???~...........................
.......................,.+77777$O?IIIIII77777777777$$$$$$$$$$$ZZOOOO777777I.........................
.....................777II7777777OZ777777$$$$$$$$$$$$$ZOOOOOOOOOOO+++++===77?.......................
...................77=+++??II777777O$$$$$ZZZZZZZOOOOOOOOOOOOOOOOZ77I+I??++==I7......................
.................,7I+?$$$$$$$$$$$$$$OOZZZZOOOOOOOOOOOOOOOOOOOOO7$$$$7+$$$$?++77.....................
.................77IZZZZ$$$$$$ZZ$$$$Z$OOOOOOOOOOOOOOOOOOOOOOOZZ$ZZZZZZ$7ZZZ$??7.....................
................I7IZZZZZZZZZZZZZZZZZZZDOOOOOOOOOOOOOOOOOOOOODOZZZZZZZZZZZZZZZI7.....................
................77OOOOOOOOOOOOOOOOOO8DOOOOOOOOOOOOOOOOOOOOOOO88OOOOOOOOOOOOOOO7.....................
................7777777777777777777D7O8888888888888888888888888DI7777777777777I.....................
.................................$O8888888888888888888888888888878..................................
................................DO88888888888888888888888888888888D.................................
..............................D$88888888888888888888888888888888888ID...............................
.............................D888888888888888888888888888888888888888D:.............................
...........................DI88888888888888888888.88888888888888888888$D............................
..........................O88888888888888888888~...,888888888DDDDDDDDD8D8...........................
...........................?8DDDDDDDDDDDDDD8DD.......8D8DDDDDDDDDDDDDDDZ............................
.............................DDDDDDDDDDDDDDD,..........DDDDDDDDDDDDDDD..............................
..............................~DDDDDDDDDDD8.............7DDDDDDDDDDDI...............................
................................DDDDDDDDD.................DDDDDDDDD.................................
..................................DDDDD7...................:DDDDD:..................................
.................................,:8DD::,,,,,,,,,,,,,,,,,,,::NDD:,..................................
................................,~=+?++=~~~~~~~~~~~~~~~~~~~=++++=~,.. ..............................
................................. ......   .   ......       ....... ................................
...DNMMM......MM ..............................M ..MMMMMMM ....=M...................................
..M$ ...N.....MM ..............................M ..M...........=M...................................
.MM..... .....MM ......MMMM....M:....M....MMMM.M ..M...........=M...... MMMM+....MI~MMMM .. MMMM....
.M............MM ....NM....M...M,....M ..M7 ..MM ..MNMMMM......=M......, ...MM...MM8 ..8 .ZM ...M. .
.M............MM.....M.....NM..M,....M .?M ....M ..M...........=M...........NM ..MN.......M.    MM..
.MD...........MM ....M.....$M..M,....M .7M.....M ..M...........=M..... MM...8M ..M=.......M.........
..M.....~.....MM ....MM....MM..MN...,M ..M,...8M ..M...........=M.....MM ...MM ..M=.......MM .......
.. MMMMM+ .~MMMMMM ...MMMMMM .. MMNM8M....MMNM+M ..M.........MMMMMMM...MM7MMNM ..M=........MMMNMM ..
....................................................................................................
....................................................................................................
.............. .....................................................................................
....................................................................................................
................................ ...................................................................
....................................................................................................
..............................................    ..................................................
................MMMMMN........................NNNM................MMMMMM...MMMMMM...................
................M=   ,M: ........................M..................MM ....MM.  .MM.................
................M=....MM... MMMI....  NMM~  .....M..................MM ....MM.... M.................
................M=... M,..8M...:M... =...IM......M..................MM ....MM....MM.................
................MMMMMM,...M.....M$ ...   .M......M..................MM ....MMMMMM,..................
................M+..OM....M.       .$MNI~~M......M..................MM ....MM.......................
................M=...MM...M$ .......M.... M......M..................MM ....MM.......................
................M=... MD ..MMI.MM ..MM .MMM...MNNMMNN.............NNMMNN ..MM.......................
............................. ............ ... ............................ ........................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
..................................... ..............................................................
............................... ................. ..................................................


'


# Configure commandline switches
Choice.options do
  header ''
  header 'Options:'

  option :file_path do
    short '-f'
    long '--file_path=FILE_PATH'
    desc "Path to target file. Can be local file or a url to plain text file. (default: #{File.expand_path File.dirname(__FILE__)}/targets.txt)"
    default File.expand_path File.dirname(__FILE__) + '/targets.txt'
  end

  option :help do
    short '-h'
    long '--help'
    desc 'Show this message'
  end
end

# Init logger
logger = Logger.new(STDOUT)

logger.formatter = proc do |severity, datetime, progname, msg|
  "[#{severity}]: #{msg}\n"
end

logger.level = Logger::INFO

# We need to disable SSL verification for windows, unless you install this cert: http://curl.haxx.se/ca/cacert.pem
# If you install that cert you should comment the next 7 lines out
if Gem.win_platform? && Choice[:file_path] =~ /\A#{URI::regexp(['http', 'https'])}\z/
  logger.warn 'Running on Windows... We need to disable ssl to download our targets.'
  original_verbosity = $VERBOSE
  $VERBOSE = nil
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
  $VERBOSE = original_verbosity
end


cfbypass = CFBypass.new

file_contents = cfbypass.hosts_to_a(Choice[:file_path], logger)

cfbypass.run(file_contents, logger)

